services:
  bot:
    build: .
    container_name: fintrackbot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=fintrackdb
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:14
    container_name: fintrackbot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrackdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net

volumes:
  pgdata:

networks:
  app_net:
    driver: bridge
